// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";
import { Suspense } from "react"; // Import Suspense from React

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "College Booking | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <Toaster />
          <div className="bg-navbar-bg shadow-sm">
            <Navbar />
          </div>
          <main className="">
            {/* Wrap children in Suspense to handle client-side components
                that cannot be pre-rendered on the server (e.g., those using useSearchParams).
                This defers rendering until the client side. */}
            <Suspense fallback={<div>Loading page...</div>}> {/* You can customize the fallback UI */}
              {children}
            </Suspense>
          </main>
          <Footer/>
        </NextAuthProvider>
      </body>
    </html>
  );
}
// 